name: "Execução Manual"
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando dependencias
        run: npm install

      - name: Instalando mochawesome
        run: npm install --save-dev mochawesome

      - name: Executando testes e2e
        run: npx mocha --reporter mochawesome

      - name: Upload do relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-mochawesome
          path: mochawesome-report/
